package addaccount;

import javafx.fxml.FXML;


import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

import javafx.scene.control.DatePicker;

public class AddaccountController {
	@FXML
	private TextField name;
	@FXML
	private TextField nid;
	@FXML
	private DatePicker birthdate;
	@FXML
	private TextField address;
	@FXML
	private TextField phone;
	@FXML
	private PasswordField password;
	@FXML
	private Button signup;

	// Event Listener on Button[#signup].onAction
	@FXML
	public void signup(ActionEvent event) {
		// TODO Autogenerated
		
		String uname=name.getText();
		String id=nid.getText();
		String addrss=address.getText();
		String phne=phone.getText();
		String pass=password.getText();
		
	}
}
